### ISSUE TITLE
Call signs not displaying on V2 livery cars

### ISSUE THREAD

**Issue by demetridigital** [CloakedManz/cm-callsign#1]
Currently have PS-Livery V2 cars, however the callsign is not displaying on the vehicles. 
![FiveM_b2699_GTAProcess_FiWKKFQtfU](https://user-images.githubusercontent.com/113472737/230030620-57b7eb0b-1aae-4221-9be1-97af8737a4e8.jpg)

**Comment by Nick5M420** [comment]
same
^

**Comment by CloakedManz** [comment]
Hey! I had no issue with this but will take a look today and check it out.

**Comment by CloakedManz** [comment]
I pushed an update. Download the code (not the release) and let me know how it goes. Are you using a framework?

**Comment by CloakedManz** [comment]
This issue has been fixed with the latest release, enjoy!
