### ISSUE TITLE
Doesn't want to work for me :(

### ISSUE THREAD

**Issue by Nick5M420** [CloakedManz/cm-callsign#5]
i have ps-livery1.0 and 2.0 in the cars work fine 
i have your newest version and read the read me on both 
the qb-target init is working in game to "set callsign" 
i think maybe im doing something wrong tho cause nothing
seems to make it show a callsign, no errors console or f8.
is there something special i need to do with the cars for this to work?
please help if you can thanks!

**Comment by CloakedManz** [comment]
Do /callsign 101 then use the QB target. You have to use that command to declare a callsign with the police job.

**Comment by Nick5M420** [comment]
yeah, i have a call sign, i did "101" when i target "set callsign" no notification no error just nothing appears, but when i did /callsign"1 0 1" its notified "must be 3 digits", im wondering do i have to mess with the files for ps-liverys to enable the callsigns? ive just redownloaded both resources to see what in the world i am doing wrong

**Comment by CloakedManz** [comment]
Follow my instructions EXACTLY NO SPACES. Do /callsign 101 then try the
target.

**Comment by Nick5M420** [comment]
![image](https://user-images.githubusercontent.com/95560411/230401050-d90707ee-8d96-4980-82b3-8c336b1fcc43.png)
![image](https://user-images.githubusercontent.com/95560411/230401160-c869a6be-9729-4943-b0fc-4410ea8f13fa.png)
![image](https://user-images.githubusercontent.com/95560411/230401221-12ea06ea-ba1c-4a48-b45a-83cc56ba7668.png)
no, i understand im just not having anything appear :/ do i have to put the files from "vehiclemods" somewhere thats in the psliverys2.0? sorry im just confused

**Comment by CloakedManz** [comment]
There is obviously an issue with either your config or your police job.
This has been tested by MULTIPLE people without issue.

**Comment by Nick5M420** [comment]
![image](https://user-images.githubusercontent.com/95560411/230402084-ee4497d2-838d-4e1b-97b5-0f3ddda0c898.png)
callsign changes everywhere else so. im not sure even the /setcallsign nothing shows on the vehicles 
sorry for the trouble i just really like this idea but after messing with it all day im just confused 
the policejob is from a fresh build about a month ago so idk maybe sorry i will keep trying.

**Comment by CloakedManz** [comment]
Show me a picture of your config.

**Comment by Nick5M420** [comment]
![image](https://user-images.githubusercontent.com/95560411/230409467-d9edface-4470-4d22-a3a7-ef1b958ebb82.png)

**Comment by CloakedManz** [comment]
Turn QBNotify to true and try it

**Comment by Nick5M420** [comment]
na nothing, even threw in a brand new pd job from the repo just to try i must just be stupid im sorry for the trouble awesome resource tho glad it works for others!

**Comment by Nick5M420** [comment]
i use jim-mechanic would this maybe require something else to work :o ?

**Comment by CloakedManz** [comment]
Try using this
https://github.com/CloakedManz/cm-callsign/releases/tag/V2.1.0

**Comment by CloakedManz** [comment]
Try turning QBTarget to false and getting in the vehicle and using
/setcallsign

**Comment by Nick5M420** [comment]
so. i can trigger every event that tells me im doing it wrong. 
"Your callsign must be 3 digits long!"
"You are not allowed to use this command!"

i swear i am doing everything right the car should be changing but its not, 
ive switched up this resource config every which way redownloaded ps-liverys 
prolly half a dozen times used every release of this 
tried a new policejob, added back qb-mechanicjob 


tried looking at jim-mechanic to see if i could maybe change it with one 
of those tools, it only shows extras and liveries as things to be done to in 
the case of this vehicle "socharger". I'm stumped after hours of leaving and coming
back to this all day i appreciate your help and contribution to the community.

I wish i could take advantage of this but my brain is dead been up to long i think. 
have a good evening/day sorry again for the troubles and thanks for trying to help! 
goodnight :D 

this will be the first thing i look at when i get up if maybe someone has any idea why this is a pain please 
reachout ty

**Comment by CloakedManz** [comment]
I recommend joining the Project Sloth discord and getting support there! https://discord.gg/projectsloth
